# Generated by Django 2.2.7 on 2020-02-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200205_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
