# Generated by Django 2.2.7 on 2019-12-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='background',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='leveltheme',
            name='background',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='background',
            field=models.ImageField(upload_to=''),
        ),
    ]
