# Generated by Django 2.2.7 on 2020-01-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200104_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название обучалки'),
        ),
    ]
