# Generated by Django 2.2.7 on 2020-01-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200104_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThemeTheme',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тема тем уровней')),
                ('background', models.ImageField(upload_to='img/', verbose_name='Фон')),
            ],
        ),
        migrations.AddField(
            model_name='leveltheme',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LevelThemeTheme', verbose_name='Тема'),
        ),
    ]
