# Generated by Django 2.2.7 on 2020-01-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200104_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название обучалки'),
        ),
    ]
