# Generated by Django 2.2.7 on 2020-01-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200106_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialtheme',
            name='theme',
        ),
        migrations.DeleteModel(
            name='TutorialThemeTheme',
        ),
    ]
