# Generated by Django 2.2.7 on 2020-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='scores',
            field=models.ManyToManyField(to='main.Scores', verbose_name='Результаты'),
        ),
    ]
