# Generated by Django 2.2.7 on 2020-02-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200204_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='level',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
