# Generated by Django 2.2.7 on 2020-01-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название обучалки')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название правила')),
                ('use_template', models.BooleanField(default=True, verbose_name='Использовать шаблон?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='levels/img/', verbose_name='Картинка')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Надпись')),
                ('audio', models.FileField(blank=True, null=True, upload_to='levels/audio/', verbose_name='Аудио')),
                ('customHTML', models.FileField(blank=True, help_text='Не работает, если включено "Использовать шаблон"', null=True, upload_to='levels/customHTML', verbose_name='Свой вариант страницы')),
                ('tutorial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutorials.Tutorial', verbose_name='Обучалка')),
            ],
        ),
    ]
