# Generated by Django 2.2.7 on 2020-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200106_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='customHTML',
            field=models.FileField(blank=True, help_text='Не работает, если включено "Использовать шаблон"', null=True, upload_to='tutorials/customHTML/', verbose_name='Свой вариант страницы'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название правила'),
        ),
    ]
