# Generated by Django 2.2.7 on 2020-01-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200106_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='theme',
            field=models.CharField(default='-', help_text='Отображается вверху страницы', max_length=10, verbose_name='Тема обучалки'),
            preserve_default=False,
        ),
    ]
