# Generated by Django 2.2.7 on 2020-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_tutorial_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='theme',
            field=models.CharField(help_text='Отображается вверху страницы', max_length=50, verbose_name='Тема обучалки'),
        ),
    ]
