# Generated by Django 2.2.7 on 2019-12-22 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название уровня:')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вопроса:')),
                ('use_template', models.BooleanField(default=True, verbose_name='Использовать шаблон?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='levels/img/', verbose_name='Картинка:')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Надпись:')),
                ('audio', models.FileField(blank=True, null=True, upload_to='levels/audio/', verbose_name='Аудио:')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.Level', verbose_name='Уровень:')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Ответ: ')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный:')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.Question', verbose_name='Вопрос:')),
            ],
        ),
    ]
