# Generated by Django 2.2.7 on 2019-12-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.IntegerField(choices=[(0, 'Один вариант ответа'), (1, 'Несколько вариантов ответа'), (2, 'Ввод ответа')], default='0', help_text='Тип вопроса'),
        ),
    ]
