# Generated by Django 2.2.7 on 2019-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_auto_20191225_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='customHTML',
            field=models.TextField(blank=True, null=True),
        ),
    ]
