# Generated by Django 2.2.7 on 2019-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_question_customhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='customHTML',
            field=models.FileField(blank=True, null=True, upload_to='levels/customHTML', verbose_name='Свой вариант страницы:'),
        ),
    ]
