# Generated by Django 2.2.7 on 2019-12-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_auto_20191225_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='customHTML',
            field=models.FileField(blank=True, help_text='Не работает, если включено "Использовать шаблон"', null=True, upload_to='levels/customHTML', verbose_name='Свой вариант страницы:'),
        ),
    ]
