# Generated by Django 2.2.7 on 2020-01-03 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_auto_20191227_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный?'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Название уровня'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='levels/audio/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='question',
            name='customHTML',
            field=models.FileField(blank=True, help_text='Не работает, если включено "Использовать шаблон"', null=True, upload_to='levels/customHTML', verbose_name='Свой вариант страницы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='levels/img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.Level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Надпись'),
        ),
    ]
