# Generated by Django 2.2.7 on 2020-01-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_auto_20200104_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ответ'),
        ),
    ]
