# Generated by Django 2.2.7 on 2020-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0008_auto_20200106_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Ответ'),
        ),
    ]
