# Generated by Django 2.2.7 on 2020-02-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_auto_20200106_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='theme',
            field=models.CharField(default='-', help_text='Отображается вверху страницы', max_length=50, verbose_name='Тема уровня'),
            preserve_default=False,
        ),
    ]
