# Generated by Django 2.2.7 on 2020-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_level_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='theme',
            field=models.CharField(help_text='Отображается вверху страницы', max_length=21, verbose_name='Тема уровня'),
        ),
    ]
